### ISSUE TITLE
cannot build

### ISSUE THREAD

**Issue by crypto-heimdall** [matteocam/CPlink#1]
Just followed instructions in README but something's not right to do with zexe.
Can you please fix that ? It depends on 'ccgro16', which cannot be found anywhere.

I appreciate it in advance.

**Comment by matteocam** [comment]
Hi,
I cleaned up a few things. Does it work now for you?

**Comment by crypto-heimdall** [comment]
Thanks for your quick response.
I'm afraid it does not work.
Here's an error message I've got when building.

fatal: repository 'https://github.com/kobigurk/cpsnarks-set-zexe.git/' not found

That repo must have been replaced or moved.

**Comment by matteocam** [comment]
It may have to do with cached submodules.
What happens if you clone the repo from scratch?

**Comment by crypto-heimdall** [comment]
![image](https://user-images.githubusercontent.com/56213390/84794157-df548b00-b030-11ea-9cd8-bb8c74647b97.png)

Is that a problem from the '.gitmodules' including the link 'https://github.com/kobigurk/cpsnarks-set-zexe.git/' which does not exist?

**Comment by matteocam** [comment]
I think I found it. Thanks again. 
I'm closing this, but feel free to open one more issue if it keeps popping up.
